load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "timeutil",
    srcs = ["timeutil.go"],
    importpath = "github.com/xytan0056/bazel-fixture/pkg/timeutil",
    visibility = ["//visibility:public"],
)

go_test(
    name = "timeutil_test",
    srcs = ["timeutil_test.go"],
    embed = [":timeutil"],
    deps = ["@com_github_stretchr_testify//assert"],
)
